# Generated by Django 5.0.4 on 2024-05-10 06:14

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_of_decision', models.DateField(default=datetime.datetime.today)),
                ('docket_number', models.CharField(blank=True, max_length=50)),
                ('respondents', models.CharField(blank=True, max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=50)),
                ('filePdf', models.FileField(upload_to='files', validators=[django.core.validators.FileExtensionValidator('pdf')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
