# Generated by Django 5.0.4 on 2024-05-09 01:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casefile',
            name='date_of_decision',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='casefile',
            name='docket_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='casefile',
            name='remarks',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='casefile',
            name='respondents',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
