# Generated by Django 5.0.4 on 2024-05-10 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='filePdf',
            field=models.FileField(upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
